name: Deploy to ECR

on:
    push:
      branches:
        - main
        
jobs:
    push-to-ecr:
        runs-on: ubuntu-latest
        env:
          DOCKER_TAG: ${{ github.ref_name }}
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
 
        - name: Log in to ECR
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

          run: |
            aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}


        - name: Build frontend-micro container
          run: |
            docker build . -t frontend-micro-container:${{ github.ref_name }}
            
        - name: tag container for ECR
          run: |
            docker tag frontend-micro-container:${{ github.ref_name }} ${{ secrets.ECR_REPOSITORY }}:${{ github.ref_name }}
 
        - name: Push labs-now container to ECR
          run: |
            docker push ${{ secrets.ECR_REPOSITORY }}:${{ github.ref_name }}